### ISSUE TITLE
Community string too long

### ISSUE THREAD

**Issue by dirtdiver512** [trailofbits/onesixtyone#1]
I get this error if the input file is 121 lines of strings

**Comment by WhiteWinterWolf** [comment]
Hello dirtdiver512,

I encountered the same issue as you. The problem does not come from the size of the file, but most likely from the fact that at least one of the community strings it contains is longer than 16 characters, the maximum size allowed by `onesixtyone`.

As per my understanding, this limitation is arbitrary, and should be raised since some devices accept and use longer community strings.

You will find attached a patch which does the following things:
- Add _"TENmanUFactOryPOWER"_ to the _dict.txt_ file. This is the default community string for some APC devices and allows to test the issue.
- Raise the maximum community string length to 32.
- Modify the definition of the `timeval_subtract()` function from `inline` to `static inline` since GCC was choking on this. I'm not sure there is any advantage in defining this function as inline, but in all cases it seems it must be explicitly defined either as `extern inline` or `static inline` to be compilable by GCC.

Regards,

[onesixtyone_issue1_toolong.patch.txt](https://github.com/trailofbits/onesixtyone/files/560171/onesixtyone_issue1_toolong.patch.txt)
